name: arabic_base
description: "Arabic learning app for beginners and children"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # SVG Support
  flutter_svg: ^2.0.9
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    # Images
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/categories/
    - assets/images/icons/
    
    # SVG Images
    - assets/images/svg/icons/
    - assets/images/svg/illustrations/
    
    # Audio Files
    - assets/audio/letters/
    - assets/audio/segments/lesson_1/
    - assets/audio/segments/lesson_2/
    - assets/audio/segments/lesson_3/
    - assets/audio/words/lesson_1/
    - assets/audio/words/lesson_2/
    - assets/audio/words/lesson_3/
    
    # Animations
    - assets/animations/
  
  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
